
# TODO: Check if logger can be enabled

defaults:
  - _self_
  - data: dogbreed
  - model: dogbreed_classifier
  - logger: default
  - paths: default
  - trainer: default
  - callbacks: default
  - hydra: default

  - experiment: dogbreed_ex

  - debug: null

task_name: "eval"
tags: ["dev"]
train: False
test: true
ckpt_path: null
seed: null
